# Generated by Django 4.2.7 on 2023-11-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_alter_invitation_recipient_alter_invitation_sender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
