# Generated by Django 4.2.7 on 2023-11-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_system_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDeviceParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_with_parameters_in_system', to='db.device')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_in_device_in_system', to='db.parameter')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_with_devices_with_parameters', to='db.system')),
            ],
        ),
    ]
