# Generated by Django 4.2.7 on 2023-11-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_alter_notification_type_participationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("invitation", "Invitation"),
                    ("system", "System Notification"),
                    ("requests", "Participation Request"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
