# Generated by Django 4.2.7 on 2023-11-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_systemdeviceparameters_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemdeviceparameters',
            unique_together={('device', 'parameter', 'system')},
        ),
    ]
