# Generated by Django 4.2.7 on 2023-11-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_systemdeviceparameters_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdeviceparameters',
            name='operator',
            field=models.CharField(choices=[('>', 'is greater than'), ('>=', 'is greater or equal'), ('<', 'is less than'), ('<=', 'is less or equal'), ('=', 'is equal')], default='>'),
        ),
    ]
