# Generated by Django 4.2.7 on 2023-11-20 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('creator', 'Creator'), ('user', 'User'), ('broker', 'Broker'), ('visitor', 'Visitor')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='system',
            name='users',
        ),
        migrations.CreateModel(
            name='UserSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems_from_user', to='db.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_with_systems', to='db.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices_from_user', to='db.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_with_devices', to='db.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SystemUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_with_users', to='db.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_in_system', to='db.system')),
            ],
        ),
        migrations.CreateModel(
            name='SystemDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices_in_system', to='db.device')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_with_devices', to='db.system')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to='db.userprofile'),
        ),
        migrations.AlterField(
            model_name='system',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_admin', to='db.userprofile'),
        ),
    ]
