# Generated by Django 4.2.7 on 2023-11-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_userprofile_remove_system_users_usersystems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
