# Generated by Django 4.2.7 on 2023-11-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_remove_userprofile_username_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system",
            name="admin",
        ),
        migrations.AddField(
            model_name="system",
            name="number_of_devices",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="system",
            name="number_of_users",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("creator", "Creator"),
                    ("user", "User"),
                    ("broker", "Broker"),
                    ("visitor", "Visitor"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
