# Generated by Django 4.2.7 on 2023-11-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_rename_device_type_device_parameters_system_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='possible_values',
            field=models.CharField(choices=[('N', 'Numeric'), ('P', 'Percentage')], default='N', max_length=16),
        ),
    ]
