# Generated by Django 4.2.7 on 2023-11-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_parameter_possible_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='value',
        ),
    ]
