# Generated by Django 4.2.7 on 2023-11-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_remove_parameter_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
