# Generated by Django 4.2.7 on 2023-11-23 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0009_invitation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitation",
            old_name="receiver",
            new_name="recipient",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="accepted",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="users",
            field=models.ManyToManyField(
                related_name="systems", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
