# Generated by Django 4.2.7 on 2023-11-24 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0010_rename_receiver_invitation_recipient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="id",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="status",
        ),
        migrations.AddField(
            model_name="invitation",
            name="notification_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="db.notification",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("invitation", "Invitation"),
                    ("system", "System Notification"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
