# Generated by Django 4.2.7 on 2023-11-25 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0010_remove_device_description_remove_device_parameters"),
        ("db", "0011_remove_invitation_id_remove_invitation_status_and_more"),
    ]

    operations = []
