# Generated by Django 4.2.7 on 2023-11-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_merge_20231125_0122'),
        ('db', '0013_remove_system_users_delete_systemusers'),
    ]

    operations = [
    ]
