# Generated by Django 4.2.7 on 2023-11-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0014_merge_20231126_1942"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("creator", "Creator"),
                    ("user", "User"),
                    ("broker", "Broker"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
